#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mercury.Droid.Resource", IsApplication=true)]

namespace Mercury.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Mercury.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Mercury.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Mercury.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Mercury.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Mercury.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Mercury.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Mercury.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Mercury.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Mercury.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Mercury.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Mercury.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Mercury.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Mercury.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Mercury.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Mercury.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AA_Buttons = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AA_ListArea = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BG_Gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IM_01_BG = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IM_02_Key = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IM_02_KeyRed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IM_02_PIN_01 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IM_02_PIN_02 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IM_02_PIN_03 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IM_02_PIN_04 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IM_02_PIN_05 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IM_02_PIN_06 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IM_02_PIN_07 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IM_02_PIN_08 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IM_02_PIN_09 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IM_02_PIN_Backspce = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IM_02_Pin_Empty = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IM_02_Pin_Full = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int IM_03_Underline = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int IM_03_UserDetails = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Incoming_Requests = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Mercury_Title = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Message = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Profile_01 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SelectLocation = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int SelectProfile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Send_Info = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Sent_Requests = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int splash = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int STENCIL_02_LogIn = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Tick = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Tick_Cross = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Underline_02 = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04001f
			public const int BUTTON_1 = 2130968607;
			
			// aapt resource value: 0x7f04001a
			public const int BUTTON_2 = 2130968602;
			
			// aapt resource value: 0x7f04001e
			public const int BUTTON_3 = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int BUTTON_4 = 2130968605;
			
			// aapt resource value: 0x7f040019
			public const int BUTTON_5 = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int BUTTON_6 = 2130968604;
			
			// aapt resource value: 0x7f040021
			public const int BUTTON_7 = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int BUTTON_8 = 2130968603;
			
			// aapt resource value: 0x7f040020
			public const int BUTTON_9 = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int BUTTON_back = 2130968610;
			
			// aapt resource value: 0x7f040032
			public const int BUTTON_button = 2130968626;
			
			// aapt resource value: 0x7f040037
			public const int BottomReqButton_Layout = 2130968631;
			
			// aapt resource value: 0x7f040031
			public const int Button_Layout = 2130968625;
			
			// aapt resource value: 0x7f040033
			public const int Buttons_Layout = 2130968627;
			
			// aapt resource value: 0x7f04003b
			public const int CANCEL_button = 2130968635;
			
			// aapt resource value: 0x7f04002a
			public const int DATE_text = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int DateBG_Layout = 2130968617;
			
			// aapt resource value: 0x7f040025
			public const int ID_Image = 2130968613;
			
			// aapt resource value: 0x7f04003e
			public const int INCOMING_REQ_listview = 2130968638;
			
			// aapt resource value: 0x7f040036
			public const int INCOMING_button = 2130968630;
			
			// aapt resource value: 0x7f040018
			public const int Key_Image = 2130968600;
			
			// aapt resource value: 0x7f04003a
			public const int LIST_listView = 2130968634;
			
			// aapt resource value: 0x7f040045
			public const int LOCATION_received_text = 2130968645;
			
			// aapt resource value: 0x7f04002e
			public const int LOCATION_text = 2130968622;
			
			// aapt resource value: 0x7f04003c
			public const int Location_LIST = 2130968636;
			
			// aapt resource value: 0x7f04002d
			public const int Location_Layout = 2130968621;
			
			// aapt resource value: 0x7f040003
			public const int MERCURY = 2130968579;
			
			// aapt resource value: 0x7f040049
			public const int MESSAGE_received_text = 2130968649;
			
			// aapt resource value: 0x7f040047
			public const int MESSAGE_title_text = 2130968647;
			
			// aapt resource value: 0x7f040039
			public const int Mercury_Layout = 2130968633;
			
			// aapt resource value: 0x7f040017
			public const int MsgCounter_Text = 2130968599;
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f04004a
			public const int OK_button = 2130968650;
			
			// aapt resource value: 0x7f04004c
			public const int PROFILEPIC_image = 2130968652;
			
			// aapt resource value: 0x7f04003f
			public const int PROFILE_PIC_image = 2130968639;
			
			// aapt resource value: 0x7f040015
			public const int ProfilePic_Image = 2130968597;
			
			// aapt resource value: 0x7f040005
			public const int Profile_LIST = 2130968581;
			
			// aapt resource value: 0x7f040038
			public const int REQUEST_button = 2130968632;
			
			// aapt resource value: 0x7f040034
			public const int ReqButtonSeparator_Layout = 2130968628;
			
			// aapt resource value: 0x7f04003d
			public const int SENT_REQ_listview = 2130968637;
			
			// aapt resource value: 0x7f040042
			public const int STATUS_received_text = 2130968642;
			
			// aapt resource value: 0x7f040030
			public const int STATUS_text = 2130968624;
			
			// aapt resource value: 0x7f040027
			public const int Seperator_Layout = 2130968615;
			
			// aapt resource value: 0x7f04002f
			public const int Status_Layout = 2130968623;
			
			// aapt resource value: 0x7f04002c
			public const int TIME_text = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int TimeBG_Layout = 2130968619;
			
			// aapt resource value: 0x7f040023
			public const int TitleLayout = 2130968611;
			
			// aapt resource value: 0x7f040035
			public const int TopReqButton_Layout = 2130968629;
			
			// aapt resource value: 0x7f040026
			public const int USERNAME_Text = 2130968614;
			
			// aapt resource value: 0x7f040040
			public const int USERNAME_text = 2130968640;
			
			// aapt resource value: 0x7f040016
			public const int USER_Text = 2130968598;
			
			// aapt resource value: 0x7f040028
			public const int UserDetails_Layout = 2130968616;
			
			// aapt resource value: 0x7f040024
			public const int UserID_Layout = 2130968612;
			
			// aapt resource value: 0x7f04004b
			public const int UserRequest_Container = 2130968651;
			
			// aapt resource value: 0x7f040007
			public const int button1 = 2130968583;
			
			// aapt resource value: 0x7f040013
			public const int button2 = 2130968595;
			
			// aapt resource value: 0x7f040055
			public const int button3 = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int button4 = 2130968662;
			
			// aapt resource value: 0x7f04000e
			public const int editText1 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int editText2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int imageView1 = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int linearLayout1 = 2130968596;
			
			// aapt resource value: 0x7f040002
			public const int relativeLayout1 = 2130968578;
			
			// aapt resource value: 0x7f040043
			public const int relativeLayout10 = 2130968643;
			
			// aapt resource value: 0x7f040046
			public const int relativeLayout11 = 2130968646;
			
			// aapt resource value: 0x7f040041
			public const int relativeLayout12 = 2130968641;
			
			// aapt resource value: 0x7f040044
			public const int relativeLayout13 = 2130968644;
			
			// aapt resource value: 0x7f040048
			public const int relativeLayout14 = 2130968648;
			
			// aapt resource value: 0x7f040053
			public const int relativeLayout15 = 2130968659;
			
			// aapt resource value: 0x7f04004e
			public const int relativeLayout19 = 2130968654;
			
			// aapt resource value: 0x7f040004
			public const int relativeLayout2 = 2130968580;
			
			// aapt resource value: 0x7f040050
			public const int relativeLayout20 = 2130968656;
			
			// aapt resource value: 0x7f040054
			public const int relativeLayout21 = 2130968660;
			
			// aapt resource value: 0x7f040006
			public const int relativeLayout3 = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int relativeLayout4 = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int relativeLayout5 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int relativeLayout6 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int relativeLayout7 = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int relativeLayout8 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int relativeLayout9 = 2130968594;
			
			// aapt resource value: 0x7f040009
			public const int textView1 = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int textView2 = 2130968589;
			
			// aapt resource value: 0x7f04004f
			public const int textView3 = 2130968655;
			
			// aapt resource value: 0x7f040051
			public const int textView4 = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int textView5 = 2130968658;
			
			// aapt resource value: 0x7f04004d
			public const int textView7 = 2130968653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int L_01_00_ProfileView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int L_01_01_Registration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int L_02_LogInView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int L_03_00_HomeView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int L_03_01_MakeRequestView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int L_03_03_LocationsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int L_04_00_RequestHomeView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int L_04_01_ReceivedRequestView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int L_04_02_AnswerRequestView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LIST_IncomingRequests = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LIST_Locations = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LIST_RequestUsers = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LIST_SentRequests = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LIST_UserProfiles = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SplashScreen = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_App = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Theme_Splash = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int button_text = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int list_item = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
