#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mercury.Droid.Resource", IsApplication=true)]

namespace Mercury.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Mercury.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Mercury.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Mercury.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Mercury.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Mercury.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Mercury.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Mercury.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Mercury.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Mercury.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Mercury.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Mercury.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Mercury.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Mercury.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Mercury.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Mercury.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Mercury.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Mercury.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::Mercury.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::Mercury.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Mercury.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Mercury.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AA_Buttons = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AA_ListArea = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BG_Gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IM_01_BG = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IM_02_Key = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IM_02_KeyRed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IM_02_PIN_01 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IM_02_PIN_02 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IM_02_PIN_03 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IM_02_PIN_04 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IM_02_PIN_05 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IM_02_PIN_06 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IM_02_PIN_07 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IM_02_PIN_08 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IM_02_PIN_09 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IM_02_PIN_Backspce = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IM_02_Pin_Empty = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IM_02_Pin_Full = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int IM_03_Underline = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int IM_03_UserDetails = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Incoming_Requests = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Mercury_Title = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Message = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Profile_01 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SelectLocation = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int SelectProfile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Send_Info = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Sent_Requests = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int splash = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int STENCIL_02_LogIn = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Tick = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Tick_Cross = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Underline_02 = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int BUTTON_1 = 2131034145;
			
			// aapt resource value: 0x7f05001c
			public const int BUTTON_2 = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int BUTTON_3 = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int BUTTON_4 = 2131034143;
			
			// aapt resource value: 0x7f05001b
			public const int BUTTON_5 = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int BUTTON_6 = 2131034142;
			
			// aapt resource value: 0x7f050023
			public const int BUTTON_7 = 2131034147;
			
			// aapt resource value: 0x7f05001d
			public const int BUTTON_8 = 2131034141;
			
			// aapt resource value: 0x7f050022
			public const int BUTTON_9 = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int BUTTON_back = 2131034148;
			
			// aapt resource value: 0x7f050034
			public const int BUTTON_button = 2131034164;
			
			// aapt resource value: 0x7f050039
			public const int BottomReqButton_Layout = 2131034169;
			
			// aapt resource value: 0x7f050033
			public const int Button_Layout = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int Buttons_Layout = 2131034165;
			
			// aapt resource value: 0x7f05003d
			public const int CANCEL_button = 2131034173;
			
			// aapt resource value: 0x7f05002c
			public const int DATE_text = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int DateBG_Layout = 2131034155;
			
			// aapt resource value: 0x7f050027
			public const int ID_Image = 2131034151;
			
			// aapt resource value: 0x7f050040
			public const int INCOMING_REQ_listview = 2131034176;
			
			// aapt resource value: 0x7f050038
			public const int INCOMING_button = 2131034168;
			
			// aapt resource value: 0x7f05001a
			public const int Key_Image = 2131034138;
			
			// aapt resource value: 0x7f05003c
			public const int LIST_listView = 2131034172;
			
			// aapt resource value: 0x7f050047
			public const int LOCATION_received_text = 2131034183;
			
			// aapt resource value: 0x7f050030
			public const int LOCATION_text = 2131034160;
			
			// aapt resource value: 0x7f05003e
			public const int Location_LIST = 2131034174;
			
			// aapt resource value: 0x7f05002f
			public const int Location_Layout = 2131034159;
			
			// aapt resource value: 0x7f050003
			public const int MERCURY = 2131034115;
			
			// aapt resource value: 0x7f05004b
			public const int MESSAGE_received_text = 2131034187;
			
			// aapt resource value: 0x7f050049
			public const int MESSAGE_title_text = 2131034185;
			
			// aapt resource value: 0x7f05003b
			public const int Mercury_Layout = 2131034171;
			
			// aapt resource value: 0x7f050019
			public const int MsgCounter_Text = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05004c
			public const int OK_button = 2131034188;
			
			// aapt resource value: 0x7f05004e
			public const int PROFILEPIC_image = 2131034190;
			
			// aapt resource value: 0x7f050041
			public const int PROFILE_PIC_image = 2131034177;
			
			// aapt resource value: 0x7f050017
			public const int ProfilePic_Image = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int Profile_LIST = 2131034117;
			
			// aapt resource value: 0x7f05003a
			public const int REQUEST_button = 2131034170;
			
			// aapt resource value: 0x7f050059
			public const int Recall = 2131034201;
			
			// aapt resource value: 0x7f050036
			public const int ReqButtonSeparator_Layout = 2131034166;
			
			// aapt resource value: 0x7f05003f
			public const int SENT_REQ_listview = 2131034175;
			
			// aapt resource value: 0x7f050044
			public const int STATUS_received_text = 2131034180;
			
			// aapt resource value: 0x7f050032
			public const int STATUS_text = 2131034162;
			
			// aapt resource value: 0x7f050029
			public const int Seperator_Layout = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int Status_Layout = 2131034161;
			
			// aapt resource value: 0x7f050058
			public const int Submit = 2131034200;
			
			// aapt resource value: 0x7f050057
			public const int TEXT_Name = 2131034199;
			
			// aapt resource value: 0x7f05005a
			public const int TEXT_Recall = 2131034202;
			
			// aapt resource value: 0x7f05002e
			public const int TIME_text = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int TimeBG_Layout = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int TitleLayout = 2131034149;
			
			// aapt resource value: 0x7f050037
			public const int TopReqButton_Layout = 2131034167;
			
			// aapt resource value: 0x7f050028
			public const int USERNAME_Text = 2131034152;
			
			// aapt resource value: 0x7f050042
			public const int USERNAME_text = 2131034178;
			
			// aapt resource value: 0x7f050018
			public const int USER_Text = 2131034136;
			
			// aapt resource value: 0x7f05002a
			public const int UserDetails_Layout = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int UserID_Layout = 2131034150;
			
			// aapt resource value: 0x7f05004d
			public const int UserRequest_Container = 2131034189;
			
			// aapt resource value: 0x7f050007
			public const int button1 = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int button2 = 2131034133;
			
			// aapt resource value: 0x7f050055
			public const int button3 = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int button4 = 2131034198;
			
			// aapt resource value: 0x7f05000f
			public const int editText1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int editText2 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int imageView1 = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout1 = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int relativeLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050045
			public const int relativeLayout10 = 2131034181;
			
			// aapt resource value: 0x7f050048
			public const int relativeLayout11 = 2131034184;
			
			// aapt resource value: 0x7f050043
			public const int relativeLayout12 = 2131034179;
			
			// aapt resource value: 0x7f050046
			public const int relativeLayout13 = 2131034182;
			
			// aapt resource value: 0x7f05004a
			public const int relativeLayout14 = 2131034186;
			
			// aapt resource value: 0x7f050053
			public const int relativeLayout15 = 2131034195;
			
			// aapt resource value: 0x7f050050
			public const int relativeLayout19 = 2131034192;
			
			// aapt resource value: 0x7f050004
			public const int relativeLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050051
			public const int relativeLayout20 = 2131034193;
			
			// aapt resource value: 0x7f050054
			public const int relativeLayout21 = 2131034196;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout3 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int relativeLayout4 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int relativeLayout5 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int relativeLayout6 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayout7 = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int relativeLayout8 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int relativeLayout9 = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int textView2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView3 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int textView4 = 2131034130;
			
			// aapt resource value: 0x7f050052
			public const int textView5 = 2131034194;
			
			// aapt resource value: 0x7f05004f
			public const int textView7 = 2131034191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int L_01_00_ProfileView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int L_01_01_Registration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int L_02_LogInView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int L_03_00_HomeView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int L_03_01_MakeRequestView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int L_03_03_LocationsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int L_04_00_RequestHomeView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int L_04_01_ReceivedRequestView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int L_04_02_AnswerRequestView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LIST_IncomingRequests = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LIST_Locations = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LIST_RequestUsers = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LIST_SentRequests = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LIST_UserProfiles = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SplashScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TEST_DB_View = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_App = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Splash = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int button_text = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int list_item = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
